### PR TITLE
Update

### PR DESCRIPTION
**Pull request by Maurice-Betzel**

### CODE REVIEW

**Review by Idrinth — CHANGES_REQUESTED** [review]
the session clustering should still be cross language. Otherwise we lose the option of building the backend in the best avaible language for the specific task

**Comment by Maurice-Betzel** [comment]
Ignite already supports sharing a session between Java containers, but not cross language. Here some integration coding needs to be done. The sharing of key-values with stateless services is not affected by this.

**Comment by Idrinth** [comment]
The session is defined as a list of objects wrapped in a HttpSession-Interface and serialized by a developer chosen method in the sevlet 3.0 final spec(the one supported by AI).
This does not change the request above, it merely means, that php-sessions need to be wrapped before serialized(as necessary in any case).
What it does, is defining the Interface to implement, you might want to add that as well https://docs.oracle.com/javaee/6/api/javax/servlet/http/HttpSession.html .

Regarding the implementation, see #11.

**Comment by Idrinth** [comment]
on a sidenote, you need to provide information on how to retrieve the session data - java has an implementation, other languages do not.

**Review by Idrinth — APPROVED** [review]

**Pull request merged**
